### PR TITLE
Better c3 lobby fix

### PR DESCRIPTION
**Pull request by cool-nite**
New pull request for this , something went wrong with the last one so i had to close the old pull request

### CODE REVIEW

**Comment by cool-nite** [comment]
(btw tell me if you get any issues with this cus idk how reliable this fix is)

**Comment by timjans01** [comment]
What was the problem

**Comment by cool-nite** [comment]
> What was the problem

if you're asking what the problem was with my old pull request it was that it stopped the playlist backgrounds from showing because i stopped fortnite from sending stuff to the cdn2.unrealengine.com or whatever it was (i forgot)

if you're asking what the problem stopping c3 from working was then it was that there was 1 request that the game makes to the servers in c3 s2 and later that wasn't being redirected to neonitev2

**Comment by cool-nite** [comment]
closed it because

A - wasn't accepted

and , more importantly

B - this is probably the worst way to do it , i need to find a better way

**Pull request closed without merging**
